Fix Wmissing-template-arg-list-after-template-kw in nano
Clang has a new warning that requires a template argument list after using the template keyword.

See llvm/llvm-project#94194 for the upstream
clang changes

```
/Users/julien/Software/Others/OpenStudio3/src/nano/nano_signal_slot.hpp:40:41: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
   40 |     Observer::insert(Delegate::template bind(instance), this);
      |                                         ^
/Users/julien/Software/Others/OpenStudio3/src/nano/nano_signal_slot.hpp:74:41: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
   74 |     Observer::remove(Delegate::template bind(instance), this);
      |                                         ^
2 errors generated.
```